// client/src/pages/Tasks.tsx
import { AppLayout } from "@/components/AppLayout";
import { useTasks, useCreateTask, useUpdateTask, useDeleteTask } from "@/hooks/use-tasks";
import { useProfile } from "@/hooks/use-business-data";
import { Button } from "@/components/ui/button";
import { Plus, GripVertical, AlertCircle, Trash2 } from "lucide-react";
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { createTaskSchema, type Task, type CreateTask } from "@shared/schema";
import { z } from "zod";
import { useToast } from "@/hooks/use-toast";
import { motion, AnimatePresence } from "framer-motion";

export default function Tasks() {
  const { data: profile } = useProfile();
  const { data: tasks, isLoading } = useTasks(profile?.business?.id);
  const [isCreateOpen, setIsCreateOpen] = useState(false);

  if (isLoading || !profile?.business?.id) return <AppLayout><div className="p-8">Loading tasks...</div></AppLayout>;

  const columns = [
    { id: "todo", title: "To Do", tasks: tasks?.filter(t => t.status === "todo") },
    { id: "in_progress", title: "In Progress", tasks: tasks?.filter(t => t.status === "in_progress") },
    { id: "done", title: "Done", tasks: tasks?.filter(t => t.status === "done") },
  ];

  return (
    <AppLayout>
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-display font-bold">Tasks</h1>
          <p className="text-muted-foreground">Manage your team's workload.</p>
        </div>
        <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2 shadow-lg shadow-primary/20">
              <Plus size={18} /> New Task
            </Button>
          </DialogTrigger>
          <CreateTaskDialog 
            businessId={profile.business.id} 
            onClose={() => setIsCreateOpen(false)} 
          />
        </Dialog>
      </div>

      <div className="grid md:grid-cols-3 gap-6 h-full items-start">
        {columns.map((col) => (
          <div key={col.id} className="bg-muted/30 rounded-2xl p-4 border border-border/50">
            <h3 className="font-semibold mb-4 px-2 flex items-center justify-between text-sm uppercase tracking-wider text-muted-foreground">
              {col.title}
              <span className="bg-background border border-border px-2 py-0.5 rounded-md text-xs">
                {col.tasks?.length || 0}
              </span>
            </h3>
            <div className="space-y-3">
              <AnimatePresence>
                {col.tasks?.map((task) => (
                  <TaskCard key={task.id} task={task} businessId={profile.business!.id} />
                ))}
              </AnimatePresence>
              {col.tasks?.length === 0 && (
                <div className="h-24 border-2 border-dashed border-border/50 rounded-xl flex items-center justify-center text-muted-foreground text-sm italic">
                  No tasks
                </div>
              )}
            </div>
          </div>
        ))}
      </div>
    </AppLayout>
  );
}

function TaskCard({ task, businessId }: { task: Task; businessId: number }) {
  const { mutate: updateTask } = useUpdateTask(businessId);
  const { mutate: deleteTask } = useDeleteTask(businessId);
  const { toast } = useToast();

  const handleStatusChange = (newStatus: string) => {
    updateTask({ id: task.id, status: newStatus as any });
  };

  return (
    <motion.div
      layout
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, scale: 0.95 }}
      className="bg-card p-4 rounded-xl border border-border shadow-sm hover:shadow-md transition-all group"
    >
      <div className="flex justify-between items-start mb-2">
        <span className={`px-2 py-1 rounded-md text-[10px] font-bold uppercase tracking-wide border ${
          task.priority === 'high' ? 'bg-red-50 text-red-600 border-red-100' :
          task.priority === 'medium' ? 'bg-amber-50 text-amber-600 border-amber-100' :
          'bg-green-50 text-green-600 border-green-100'
        }`}>
          {task.priority}
        </span>
        <button 
          onClick={() => {
            if (confirm("Delete this task?")) {
              deleteTask(task.id);
              toast({ title: "Task deleted" });
            }
          }}
          className="text-muted-foreground hover:text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
        >
          <Trash2 size={14} />
        </button>
      </div>
      <h4 className="font-semibold text-foreground mb-1">{task.title}</h4>
      <p className="text-xs text-muted-foreground line-clamp-2 mb-4">
        {task.description || "No description"}
      </p>
      
      <div className="flex gap-2">
        {task.status !== 'todo' && (
          <Button 
            variant="outline" 
            size="sm" 
            className="h-7 text-xs flex-1"
            onClick={() => handleStatusChange('todo')}
          >
            ← Todo
          </Button>
        )}
        {task.status !== 'in_progress' && (
          <Button 
            variant="outline" 
            size="sm" 
            className="h-7 text-xs flex-1"
            onClick={() => handleStatusChange('in_progress')}
          >
            {task.status === 'todo' ? 'Start' : '← WIP'}
          </Button>
        )}
        {task.status !== 'done' && (
          <Button 
            variant="outline" 
            size="sm" 
            className="h-7 text-xs flex-1 bg-green-50 hover:bg-green-100 text-green-700 border-green-200"
            onClick={() => handleStatusChange('done')}
          >
            Done ✓
          </Button>
        )}
      </div>
    </motion.div>
  );
}

function CreateTaskDialog({ businessId, onClose }: { businessId: number, onClose: () => void }) {
  const { mutate: createTask, isPending } = useCreateTask(businessId);
  const { toast } = useToast();
  
  const form = useForm<CreateTask>({
    resolver: zodResolver(createTaskSchema),
    defaultValues: {
      title: "",
      description: "",
      priority: "medium",
      status: "todo"
    }
  });

  const onSubmit = (data: CreateTask) => {
    createTask(data, {
      onSuccess: () => {
        toast({ title: "Task created successfully" });
        onClose();
      },
      onError: () => {
        toast({ title: "Failed to create task", variant: "destructive" });
      }
    });
  };

  return (
    <DialogContent className="sm:max-w-[425px]">
      <DialogHeader>
        <DialogTitle>Create New Task</DialogTitle>
      </DialogHeader>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 pt-4">
        <div className="space-y-2">
          <label className="text-sm font-medium">Title</label>
          <Input {...form.register("title")} placeholder="e.g. Update homepage banner" />
          {form.formState.errors.title && <p className="text-xs text-destructive">{form.formState.errors.title.message}</p>}
        </div>
        
        <div className="space-y-2">
          <label className="text-sm font-medium">Description</label>
          <Textarea {...form.register("description")} placeholder="Add details..." />
        </div>

        <div className="space-y-2">
          <label className="text-sm font-medium">Priority</label>
          <Select 
            defaultValue="medium" 
            onValueChange={(val) => form.setValue("priority", val as any)}
          >
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="low">Low</SelectItem>
              <SelectItem value="medium">Medium</SelectItem>
              <SelectItem value="high">High</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <DialogFooter className="pt-4">
          <Button type="button" variant="ghost" onClick={onClose}>Cancel</Button>
          <Button type="submit" disabled={isPending}>
            {isPending ? "Creating..." : "Create Task"}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  );
}

// client/src/app/pages/tasks/tasks.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AppLayoutComponent } from '../../components/app-layout/app-layout.component';
import { BusinessService } from '../../services/business.service';
import { TaskService, Task, CreateTask } from '../../services/task.service';

@Component({
  selector: 'app-tasks',
  standalone: true,
  imports: [CommonModule, FormsModule, AppLayoutComponent],
  template: `
    <app-layout>
      <div class="space-y-6">
        <!-- Header -->
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-3xl font-bold text-gray-900">Tasks</h2>
            <p class="text-gray-500 mt-1">Manage and track your team's work</p>
          </div>
          <button (click)="showCreateModal = true"
                  class="px-4 py-2 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition-colors flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
            </svg>
            Add Task
          </button>
        </div>

        <!-- Task Columns -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <!-- To Do -->
          <div class="bg-gray-50 rounded-xl p-4">
            <h3 class="font-semibold text-gray-700 mb-4 flex items-center gap-2">
              <span class="w-3 h-3 bg-yellow-400 rounded-full"></span>
              To Do ({{ todoTasks.length }})
            </h3>
            <div class="space-y-3">
              <div *ngFor="let task of todoTasks"
                   class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                <div class="flex items-start justify-between gap-2">
                  <h4 class="font-medium text-gray-900">{{ task.title }}</h4>
                  <span [ngClass]="{
                    'bg-red-100 text-red-700': task.priority === 'high',
                    'bg-yellow-100 text-yellow-700': task.priority === 'medium',
                    'bg-gray-100 text-gray-600': task.priority === 'low'
                  }" class="px-2 py-0.5 rounded text-xs font-medium">
                    {{ task.priority }}
                  </span>
                </div>
                <p *ngIf="task.description" class="text-sm text-gray-500 mt-2">{{ task.description }}</p>
                <div class="mt-3 flex gap-2">
                  <button (click)="updateStatus(task, 'in_progress')"
                          class="text-xs text-indigo-600 hover:text-indigo-800">Start →</button>
                  <button (click)="deleteTask(task)"
                          class="text-xs text-red-600 hover:text-red-800">Delete</button>
                </div>
              </div>
              <div *ngIf="todoTasks.length === 0" class="text-center py-8 text-gray-400 text-sm">
                No tasks to do
              </div>
            </div>
          </div>

          <!-- In Progress -->
          <div class="bg-gray-50 rounded-xl p-4">
            <h3 class="font-semibold text-gray-700 mb-4 flex items-center gap-2">
              <span class="w-3 h-3 bg-blue-400 rounded-full"></span>
              In Progress ({{ inProgressTasks.length }})
            </h3>
            <div class="space-y-3">
              <div *ngFor="let task of inProgressTasks"
                   class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition-shadow">
                <div class="flex items-start justify-between gap-2">
                  <h4 class="font-medium text-gray-900">{{ task.title }}</h4>
                  <span [ngClass]="{
                    'bg-red-100 text-red-700': task.priority === 'high',
                    'bg-yellow-100 text-yellow-700': task.priority === 'medium',
                    'bg-gray-100 text-gray-600': task.priority === 'low'
                  }" class="px-2 py-0.5 rounded text-xs font-medium">
                    {{ task.priority }}
                  </span>
                </div>
                <p *ngIf="task.description" class="text-sm text-gray-500 mt-2">{{ task.description }}</p>
                <div class="mt-3 flex gap-2">
                  <button (click)="updateStatus(task, 'done')"
                          class="text-xs text-green-600 hover:text-green-800">Complete ✓</button>
                  <button (click)="updateStatus(task, 'todo')"
                          class="text-xs text-gray-600 hover:text-gray-800">← Back</button>
                </div>
              </div>
              <div *ngIf="inProgressTasks.length === 0" class="text-center py-8 text-gray-400 text-sm">
                No tasks in progress
              </div>
            </div>
          </div>

          <!-- Done -->
          <div class="bg-gray-50 rounded-xl p-4">
            <h3 class="font-semibold text-gray-700 mb-4 flex items-center gap-2">
              <span class="w-3 h-3 bg-green-400 rounded-full"></span>
              Done ({{ doneTasks.length }})
            </h3>
            <div class="space-y-3">
              <div *ngFor="let task of doneTasks"
                   class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm opacity-75">
                <div class="flex items-start justify-between gap-2">
                  <h4 class="font-medium text-gray-900 line-through">{{ task.title }}</h4>
                </div>
                <div class="mt-3 flex gap-2">
                  <button (click)="updateStatus(task, 'in_progress')"
                          class="text-xs text-gray-600 hover:text-gray-800">Reopen</button>
                  <button (click)="deleteTask(task)"
                          class="text-xs text-red-600 hover:text-red-800">Delete</button>
                </div>
              </div>
              <div *ngIf="doneTasks.length === 0" class="text-center py-8 text-gray-400 text-sm">
                No completed tasks
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Create Task Modal -->
      <div *ngIf="showCreateModal" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
        <div class="bg-white rounded-xl p-6 w-full max-w-md shadow-xl">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">Create New Task</h3>
          <form (ngSubmit)="createTask()">
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Title</label>
                <input [(ngModel)]="newTask.title" name="title" required
                       class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                       placeholder="Task title">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea [(ngModel)]="newTask.description" name="description"
                          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                          rows="3" placeholder="Task description"></textarea>
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Priority</label>
                <select [(ngModel)]="newTask.priority" name="priority"
                        class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500">
                  <option value="low">Low</option>
                  <option value="medium">Medium</option>
                  <option value="high">High</option>
                </select>
              </div>
            </div>
            <div class="flex justify-end gap-3 mt-6">
              <button type="button" (click)="showCreateModal = false"
                      class="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors">
                Cancel
              </button>
              <button type="submit"
                      class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors">
                Create Task
              </button>
            </div>
          </form>
        </div>
      </div>
    </app-layout>
  `,
  styles: []
})
export class TasksComponent implements OnInit {
  private businessService = inject(BusinessService);
  private taskService = inject(TaskService);

  tasks: Task[] = [];
  showCreateModal = false;
  businessId: number | null = null;

  newTask: CreateTask = {
    title: '',
    description: '',
    priority: 'medium',
    status: 'todo'
  };

  get todoTasks(): Task[] {
    return this.tasks.filter(t => t.status === 'todo');
  }

  get inProgressTasks(): Task[] {
    return this.tasks.filter(t => t.status === 'in_progress');
  }

  get doneTasks(): Task[] {
    return this.tasks.filter(t => t.status === 'done');
  }

  ngOnInit() {
    this.businessService.loadProfile().subscribe(profile => {
      if (profile?.businessId) {
        this.businessId = profile.businessId;
        this.taskService.loadTasks(profile.businessId).subscribe(tasks => this.tasks = tasks);
      }
    });
  }

  createTask() {
    if (!this.businessId || !this.newTask.title) return;

    this.taskService.createTask(this.businessId, this.newTask).subscribe(() => {
      this.showCreateModal = false;
      this.newTask = { title: '', description: '', priority: 'medium', status: 'todo' };
      this.taskService.loadTasks(this.businessId!).subscribe(tasks => this.tasks = tasks);
    });
  }

  updateStatus(task: Task, status: 'todo' | 'in_progress' | 'done') {
    if (!this.businessId) return;
    this.taskService.updateTask(this.businessId, task.id, { status }).subscribe(() => {
      this.taskService.loadTasks(this.businessId!).subscribe(tasks => this.tasks = tasks);
    });
  }

  deleteTask(task: Task) {
    if (!this.businessId || !confirm('Delete this task?')) return;
    this.taskService.deleteTask(this.businessId, task.id).subscribe(() => {
      this.taskService.loadTasks(this.businessId!).subscribe(tasks => this.tasks = tasks);
    });
  }
}
