// client/src/app/pages/customers/customers.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AppLayoutComponent } from '../../components/app-layout/app-layout.component';
import { BusinessService } from '../../services/business.service';
import { CustomerService, Customer, CreateCustomer } from '../../services/customer.service';

@Component({
  selector: 'app-customers',
  standalone: true,
  imports: [CommonModule, FormsModule, AppLayoutComponent],
  template: `
    <app-layout>
      <div class="space-y-6">
        <!-- Header -->
        <div class="flex items-center justify-between">
          <div>
            <h2 class="text-3xl font-bold text-gray-900">Customers</h2>
            <p class="text-gray-500 mt-1">Manage your customer relationships</p>
          </div>
          <button (click)="showCreateModal = true"
                  class="px-4 py-2 bg-indigo-600 text-white rounded-lg font-medium hover:bg-indigo-700 transition-colors flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
            </svg>
            Add Customer
          </button>
        </div>

        <!-- Search -->
        <div class="relative">
          <svg class="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"/>
          </svg>
          <input [(ngModel)]="searchTerm"
                 class="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                 placeholder="Search customers...">
        </div>

        <!-- Customer Table -->
        <div class="bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
          <table class="w-full">
            <thead class="bg-gray-50 border-b border-gray-200">
              <tr>
                <th class="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>
                <th class="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
                <th class="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">Phone</th>
                <th class="text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase tracking-wider">Notes</th>
                <th class="px-6 py-3"></th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-100">
              <tr *ngFor="let customer of filteredCustomers" class="hover:bg-gray-50">
                <td class="px-6 py-4">
                  <div class="flex items-center gap-3">
                    <div class="w-10 h-10 bg-indigo-100 rounded-full flex items-center justify-center">
                      <span class="text-indigo-700 font-medium">{{ customer.name[0] | uppercase }}</span>
                    </div>
                    <span class="font-medium text-gray-900">{{ customer.name }}</span>
                  </div>
                </td>
                <td class="px-6 py-4 text-gray-600">{{ customer.email || '-' }}</td>
                <td class="px-6 py-4 text-gray-600">{{ customer.phone || '-' }}</td>
                <td class="px-6 py-4 text-gray-500 text-sm max-w-xs truncate">{{ customer.notes || '-' }}</td>
                <td class="px-6 py-4 text-right">
                  <button (click)="deleteCustomer(customer)"
                          class="text-red-600 hover:text-red-800 text-sm">Delete</button>
                </td>
              </tr>
              <tr *ngIf="filteredCustomers.length === 0">
                <td colspan="5" class="px-6 py-12 text-center text-gray-500">
                  <div *ngIf="searchTerm">No customers found matching "{{ searchTerm }}"</div>
                  <div *ngIf="!searchTerm">No customers yet. Add your first customer!</div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Create Customer Modal -->
      <div *ngIf="showCreateModal" class="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
        <div class="bg-white rounded-xl p-6 w-full max-w-md shadow-xl">
          <h3 class="text-lg font-semibold text-gray-900 mb-4">Add Customer</h3>
          <form (ngSubmit)="createCustomer()">
            <div class="space-y-4">
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Name *</label>
                <input [(ngModel)]="newCustomer.name" name="name" required
                       class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                       placeholder="John Doe">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
                <input [(ngModel)]="newCustomer.email" name="email" type="email"
                       class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                       placeholder="john@example.com">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Phone</label>
                <input [(ngModel)]="newCustomer.phone" name="phone"
                       class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                       placeholder="+1 234 567 8900">
              </div>
              <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                <textarea [(ngModel)]="newCustomer.notes" name="notes"
                          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                          rows="3" placeholder="Additional notes..."></textarea>
              </div>
            </div>
            <div class="flex justify-end gap-3 mt-6">
              <button type="button" (click)="showCreateModal = false"
                      class="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors">
                Cancel
              </button>
              <button type="submit"
                      class="px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors">
                Add Customer
              </button>
            </div>
          </form>
        </div>
      </div>
    </app-layout>
  `,
  styles: []
})
export class CustomersComponent implements OnInit {
  private businessService = inject(BusinessService);
  private customerService = inject(CustomerService);

  customers: Customer[] = [];
  showCreateModal = false;
  searchTerm = '';
  businessId: number | null = null;

  newCustomer: CreateCustomer = {
    name: '',
    email: '',
    phone: '',
    notes: ''
  };

  get filteredCustomers(): Customer[] {
    if (!this.searchTerm) return this.customers;
    const term = this.searchTerm.toLowerCase();
    return this.customers.filter(c =>
      c.name.toLowerCase().includes(term) ||
      c.email?.toLowerCase().includes(term) ||
      c.phone?.includes(term)
    );
  }

  ngOnInit() {
    this.businessService.loadProfile().subscribe(profile => {
      if (profile?.businessId) {
        this.businessId = profile.businessId;
        this.customerService.loadCustomers(profile.businessId).subscribe(customers => this.customers = customers);
      }
    });
  }

  createCustomer() {
    if (!this.businessId || !this.newCustomer.name) return;

    this.customerService.createCustomer(this.businessId, this.newCustomer).subscribe(() => {
      this.showCreateModal = false;
      this.newCustomer = { name: '', email: '', phone: '', notes: '' };
      this.customerService.loadCustomers(this.businessId!).subscribe(customers => this.customers = customers);
    });
  }

  deleteCustomer(customer: Customer) {
    if (!this.businessId || !confirm(`Delete ${customer.name}?`)) return;
    this.customerService.deleteCustomer(this.businessId, customer.id).subscribe(() => {
      this.customerService.loadCustomers(this.businessId!).subscribe(customers => this.customers = customers);
    });
  }
}

// client/src/pages/Customers.tsx
import { AppLayout } from "@/components/AppLayout";
import { useCustomers, useCreateCustomer } from "@/hooks/use-customers";
import { useProfile } from "@/hooks/use-business-data";
import { Button } from "@/components/ui/button";
import { Plus, Search, Mail, Phone, MoreHorizontal } from "lucide-react";
import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { createCustomerSchema, type CreateCustomer } from "@shared/schema";
import { z } from "zod";
import { useToast } from "@/hooks/use-toast";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";

export default function Customers() {
  const { data: profile } = useProfile();
  const { data: customers, isLoading } = useCustomers(profile?.business?.id);
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [search, setSearch] = useState("");

  if (isLoading || !profile?.business?.id) return <AppLayout><div className="p-8">Loading...</div></AppLayout>;

  const filteredCustomers = customers?.filter(c => 
    c.name.toLowerCase().includes(search.toLowerCase()) || 
    c.email?.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <AppLayout>
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-3xl font-display font-bold">Customers</h1>
          <p className="text-muted-foreground">Manage your client relationships.</p>
        </div>
        <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2 shadow-lg shadow-primary/20">
              <Plus size={18} /> Add Customer
            </Button>
          </DialogTrigger>
          <CreateCustomerDialog 
            businessId={profile.business.id} 
            onClose={() => setIsCreateOpen(false)} 
          />
        </Dialog>
      </div>

      <div className="bg-card rounded-2xl border border-border shadow-sm overflow-hidden">
        <div className="p-4 border-b border-border flex gap-4">
          <div className="relative flex-1 max-w-sm">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground w-4 h-4" />
            <Input 
              placeholder="Search customers..." 
              className="pl-9 bg-muted/20 border-border/50"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
          </div>
        </div>
        
        <Table>
          <TableHeader>
            <TableRow className="hover:bg-transparent">
              <TableHead>Customer</TableHead>
              <TableHead>Email</TableHead>
              <TableHead>Phone</TableHead>
              <TableHead>Added</TableHead>
              <TableHead className="w-[50px]"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredCustomers?.length === 0 ? (
              <TableRow>
                <TableCell colSpan={5} className="h-32 text-center text-muted-foreground">
                  No customers found.
                </TableCell>
              </TableRow>
            ) : (
              filteredCustomers?.map((customer) => (
                <TableRow key={customer.id} className="hover:bg-muted/30">
                  <TableCell>
                    <div className="flex items-center gap-3">
                      <Avatar className="w-9 h-9 border border-border">
                        <AvatarFallback className="bg-primary/10 text-primary text-xs">
                          {customer.name.substring(0, 2).toUpperCase()}
                        </AvatarFallback>
                      </Avatar>
                      <span className="font-medium">{customer.name}</span>
                    </div>
                  </TableCell>
                  <TableCell className="text-muted-foreground">
                    <div className="flex items-center gap-2">
                      <Mail size={14} />
                      {customer.email || "-"}
                    </div>
                  </TableCell>
                  <TableCell className="text-muted-foreground">
                    <div className="flex items-center gap-2">
                      <Phone size={14} />
                      {customer.phone || "-"}
                    </div>
                  </TableCell>
                  <TableCell className="text-muted-foreground text-sm">
                    {new Date(customer.createdAt!).toLocaleDateString()}
                  </TableCell>
                  <TableCell>
                    <Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground">
                      <MoreHorizontal size={16} />
                    </Button>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </div>
    </AppLayout>
  );
}

function CreateCustomerDialog({ businessId, onClose }: { businessId: number, onClose: () => void }) {
  const { mutate: createCustomer, isPending } = useCreateCustomer(businessId);
  const { toast } = useToast();
  
  const form = useForm<CreateCustomer>({
    resolver: zodResolver(createCustomerSchema),
    defaultValues: {
      name: "",
      email: "",
      phone: "",
      notes: ""
    }
  });

  const onSubmit = (data: CreateCustomer) => {
    createCustomer(data, {
      onSuccess: () => {
        toast({ title: "Customer added" });
        onClose();
      },
      onError: () => {
        toast({ title: "Failed to add customer", variant: "destructive" });
      }
    });
  };

  return (
    <DialogContent className="sm:max-w-[425px]">
      <DialogHeader>
        <DialogTitle>Add Customer</DialogTitle>
      </DialogHeader>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4 pt-4">
        <div className="space-y-2">
          <label className="text-sm font-medium">Name</label>
          <Input {...form.register("name")} placeholder="John Doe" />
          {form.formState.errors.name && <p className="text-xs text-destructive">{form.formState.errors.name.message}</p>}
        </div>
        
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">Email</label>
            <Input {...form.register("email")} placeholder="john@example.com" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">Phone</label>
            <Input {...form.register("phone")} placeholder="+1 234..." />
          </div>
        </div>
        
        <div className="space-y-2">
          <label className="text-sm font-medium">Notes</label>
          <Input {...form.register("notes")} placeholder="Additional details..." />
        </div>

        <DialogFooter className="pt-4">
          <Button type="button" variant="ghost" onClick={onClose}>Cancel</Button>
          <Button type="submit" disabled={isPending}>
            {isPending ? "Adding..." : "Add Customer"}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  );
}
